package mx.com.kaizentec.erp.cadAnd.entidades.alumnos;
// Generated 10/02/2023 01:06:03 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TAlumnos generated by hbm2java
 */
public class TAlumnos  implements java.io.Serializable {


     private Integer idTUsuarios;
     private String nombre;
     private String apPaterno;
     private String apMaterno;
     private Integer activo;
     private Set TCalificacioneses = new HashSet(0);

    public TAlumnos() {
    }

    public TAlumnos(String nombre, String apPaterno, String apMaterno, Integer activo, Set TCalificacioneses) {
       this.nombre = nombre;
       this.apPaterno = apPaterno;
       this.apMaterno = apMaterno;
       this.activo = activo;
       this.TCalificacioneses = TCalificacioneses;
    }
   
    public Integer getIdTUsuarios() {
        return this.idTUsuarios;
    }
    
    public void setIdTUsuarios(Integer idTUsuarios) {
        this.idTUsuarios = idTUsuarios;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApPaterno() {
        return this.apPaterno;
    }
    
    public void setApPaterno(String apPaterno) {
        this.apPaterno = apPaterno;
    }
    public String getApMaterno() {
        return this.apMaterno;
    }
    
    public void setApMaterno(String apMaterno) {
        this.apMaterno = apMaterno;
    }
    public Integer getActivo() {
        return this.activo;
    }
    
    public void setActivo(Integer activo) {
        this.activo = activo;
    }
    public Set getTCalificacioneses() {
        return this.TCalificacioneses;
    }
    
    public void setTCalificacioneses(Set TCalificacioneses) {
        this.TCalificacioneses = TCalificacioneses;
    }




}


