package mx.com.kaizentec.erp.cadAnd.entidades.alumnos;
// Generated 10/02/2023 01:06:03 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TMaterias generated by hbm2java
 */
public class TMaterias  implements java.io.Serializable {


     private Integer idTMaterias;
     private String nombre;
     private Integer activo;
     private Set TCalificacioneses = new HashSet(0);

    public TMaterias() {
    }

    public TMaterias(String nombre, Integer activo, Set TCalificacioneses) {
       this.nombre = nombre;
       this.activo = activo;
       this.TCalificacioneses = TCalificacioneses;
    }
   
    public Integer getIdTMaterias() {
        return this.idTMaterias;
    }
    
    public void setIdTMaterias(Integer idTMaterias) {
        this.idTMaterias = idTMaterias;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getActivo() {
        return this.activo;
    }
    
    public void setActivo(Integer activo) {
        this.activo = activo;
    }
    public Set getTCalificacioneses() {
        return this.TCalificacioneses;
    }
    
    public void setTCalificacioneses(Set TCalificacioneses) {
        this.TCalificacioneses = TCalificacioneses;
    }




}


