package mx.com.kaizentec.erp.coreAnd.entidades.alumnos;
// Generated 10/02/2023 01:06:03 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TAlumnos generated by hbm2java
 */
public class TAlumnosDTB  {


     public Integer idTUsuarios;
     public String nombre;
     public String apPaterno;
     public String apMaterno;
     public Integer activo;

    public TAlumnosDTB() {
    }

    public TAlumnosDTB(Integer idTUsuarios, String nombre, String apPaterno, String apMaterno, Integer activo) {
        this.idTUsuarios = idTUsuarios;
        this.nombre = nombre;
        this.apPaterno = apPaterno;
        this.apMaterno = apMaterno;
        this.activo = activo;
    }

    public Integer getIdTUsuarios() {
        return idTUsuarios;
    }

    public void setIdTUsuarios(Integer idTUsuarios) {
        this.idTUsuarios = idTUsuarios;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApPaterno() {
        return apPaterno;
    }

    public void setApPaterno(String apPaterno) {
        this.apPaterno = apPaterno;
    }

    public String getApMaterno() {
        return apMaterno;
    }

    public void setApMaterno(String apMaterno) {
        this.apMaterno = apMaterno;
    }

    public Integer getActivo() {
        return activo;
    }

    public void setActivo(Integer activo) {
        this.activo = activo;
    }

   

}


