package mx.com.kaizentec.erp.coreAnd.entidades.alumnos;
// Generated 10/02/2023 01:06:03 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * TCalificaciones generated by hbm2java
 */
public class TCalificacionesDTB{


     public Integer idTCalificaciones;
     public String alumnoNombre;
     public Integer alumnoId;
     public String materiaNombre;
     public Integer materiaId;
     public BigDecimal calificacion;
     public String fechaRegistro;

    public TCalificacionesDTB() {
    }

    public Integer getIdTCalificaciones() {
        return idTCalificaciones;
    }

    public void setIdTCalificaciones(Integer idTCalificaciones) {
        this.idTCalificaciones = idTCalificaciones;
    }

    public String getAlumnoNombre() {
        return alumnoNombre;
    }

    public void setAlumnoNombre(String alumnoNombre) {
        this.alumnoNombre = alumnoNombre;
    }

    public Integer getAlumnoId() {
        return alumnoId;
    }

    public void setAlumnoId(Integer alumnoId) {
        this.alumnoId = alumnoId;
    }

    public String getMateriaNombre() {
        return materiaNombre;
    }

    public void setMateriaNombre(String materiaNombre) {
        this.materiaNombre = materiaNombre;
    }

    public BigDecimal getCalificacion() {
        return calificacion;
    }

    public void setCalificacion(BigDecimal calificacion) {
        this.calificacion = calificacion;
    }

    public String getFechaRegistro() {
        return fechaRegistro;
    }

    public void setFechaRegistro(String fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    public Integer getMateriaId() {
        return materiaId;
    }

    public void setMateriaId(Integer materiaId) {
        this.materiaId = materiaId;
    }

    

}


