package mx.com.kaizentec.erp.coreAnd.entidades.alumnos;
// Generated 10/02/2023 01:06:03 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TMaterias generated by hbm2java
 */
public class TMateriasDTB {


     public Integer idTMaterias;
     public String nombre;
     public Integer activo;

    public TMateriasDTB(Integer idTMaterias, String nombre, Integer activo) {
        this.idTMaterias = idTMaterias;
        this.nombre = nombre;
        this.activo = activo;
    }

    public TMateriasDTB() {
    }

    public Integer getIdTMaterias() {
        return idTMaterias;
    }

    public void setIdTMaterias(Integer idTMaterias) {
        this.idTMaterias = idTMaterias;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Integer getActivo() {
        return activo;
    }

    public void setActivo(Integer activo) {
        this.activo = activo;
    }



}


